# Database dir is the directory you want to store your databases in.
# It can be a git repo, but doesn't have to be...
DatabaseDir: /home/username/git/databases

# RealDatabase is the legit database
RealDatabase: balesDatabase.db

# TestDatabase is a database you can use to test features
TestDatabase: balesTestDatabase.db
